apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-6mtv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-6mtv
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-6mtv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-6mtv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-6mtv
    spec:
      containers:
      - image: quay.io/qijing/dev-release-team-tenant/appstudio/dc-metro-map-6mtv@sha256:17e14feb5dcdc673f9b2f4504197e34c49d2960227fca4c025e8b8bf04ca0c16
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
